# Generated by Django 3.2 on 2024-12-07 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20241206_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Никнейм содержит недопустимые символы', regex='^[\\w.@+-]+$')], verbose_name='Никнейм'),
        ),
    ]
