# Generated by Django 3.2 on 2024-12-10 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
    ]
